const std = @import("std");
const jconfig = @import("../root.zig").jconfig;

pub const send_events = @import("./event_data/send_events.zig");
pub const receive_events = @import("./event_data/receive_events.zig");

pub const ReceiveEventData = union(enum) {
    hello: receive_events.Hello,
    ready: receive_events.Ready,
    resumed: receive_events.Resumed,
    reconnect: receive_events.Reconnect,
    heartbeat_ack: receive_events.HeartbeatACK,
    invalid_session: receive_events.InvalidSession,
    application_command_permissions_update: receive_events.ApplicationCommandPermissionsUpdate,
    auto_moderation_rule_create: receive_events.AutoModerationRuleCreate,
    auto_moderation_rule_update: receive_events.AutoModerationRuleUpdate,
    auto_moderation_rule_delete: receive_events.AutoModerationRuleDelete,
    auto_moderation_action_execution: receive_events.AutoModerationActionExecution,
    channel_create: receive_events.ChannelCreate,
    channel_update: receive_events.ChannelUpdate,
    channel_delete: receive_events.ChannelDelete,
    thread_create: receive_events.ThreadCreate,
    thread_update: receive_events.ThreadUpdate,
    thread_delete: receive_events.ThreadDelete,
    thread_list_sync: receive_events.ThreadListSync,
    thread_member_update: receive_events.ThreadMemberUpdate,
    thread_members_update: receive_events.ThreadMembersUpdate,
    entitlement_create: receive_events.EntitlementCreate,
    entitlement_update: receive_events.EntitlementUpdate,
    entitlement_delete: receive_events.EntitlementDelete,
    guild_create: receive_events.GuildCreate,
    guild_update: receive_events.GuildUpdate,
    guild_delete: receive_events.GuildDelete,
    guild_audit_log_entry_create: receive_events.GuildAuditLogEntryCreate,
    guild_ban_add: receive_events.GuildBanAdd,
    guild_ban_remove: receive_events.GuildBanRemove,
    guild_emojis_update: receive_events.GuildEmojisUpdate,
    guild_stickers_update: receive_events.GuildStickersUpdate,
    guild_integrations_update: receive_events.GuildIntegrationsUpdate,
    guild_member_add: receive_events.GuildMemberAdd,
    guild_member_remove: receive_events.GuildMemberRemove,
    guild_member_update: receive_events.GuildMemberUpdate,
    guild_members_chunk: receive_events.GuildMembersChunk,
    guild_role_create: receive_events.GuildRoleCreate,
    guild_role_update: receive_events.GuildRoleUpdate,
    guild_role_delete: receive_events.GuildRoleDelete,
    guild_scheduled_event_create: receive_events.GuildScheduledEventCreate,
    guild_scheduled_event_update: receive_events.GuildScheduledEventUpdate,
    guild_scheduled_event_delete: receive_events.GuildScheduledEventDelete,
    guild_scheduled_event_user_add: receive_events.GuildScheduledEventUserAdd,
    guild_scheduled_event_user_remove: receive_events.GuildScheduledEventUserRemove,
    guild_soundboard_sound_create: receive_events.GuildSoundboardSoundCreate,
    guild_soundboard_sound_update: receive_events.GuildSoundboardSoundUpdate,
    guild_soundboard_sound_delete: receive_events.GuildSoundboardSoundDelete,
    guild_soundboard_sounds_update: receive_events.GuildSoundboardSoundsUpdate,
    soundboard_sounds: receive_events.SoundboardSounds,
    integration_create: receive_events.IntegrationCreate,
    integration_update: receive_events.IntegrationUpdate,
    integration_delete: receive_events.IntegrationDelete,
    interaction_create: receive_events.InteractionCreate,
    invite_create: receive_events.InviteCreate,
    invite_delete: receive_events.InviteDelete,
    message_create: receive_events.MessageCreate,
    message_update: receive_events.MessageUpdate,
    message_delete: receive_events.MessageDelete,
    message_delete_bulk: receive_events.MessageDeleteBulk,
    message_reaction_add: receive_events.MessageReactionAdd,
    message_reaction_remove: receive_events.MessageReactionRemove,
    message_reaction_remove_all: receive_events.MessageReactionRemoveAll,
    message_reaction_remove_emoji: receive_events.MessageReactionRemoveEmoji,
    presence_update: receive_events.PresenceUpdate,
    stage_instance_create: receive_events.StageInstanceCreate,
    stage_instance_update: receive_events.StageInstanceUpdate,
    stage_instance_delete: receive_events.StageInstanceDelete,
    subscription_create: receive_events.SubscriptionCreate,
    subscription_update: receive_events.SubscriptionUpdate,
    subscription_delete: receive_events.SubscriptionDelete,
    typing_start: receive_events.TypingStart,
    user_update: receive_events.UserUpdate,
    voice_channel_effect_send: receive_events.VoiceChannelEffectSend,
    voice_state_update: receive_events.VoiceStateUpdate,
    voice_server_update: receive_events.VoiceServerUpdate,
    webhooks_update: receive_events.WebhooksUpdate,
    message_poll_vote_add: receive_events.MessagePollVoteAdd,
    message_poll_vote_remove: receive_events.MessagePollVoteRemove,
    undocumented: receive_events.Undocumented,
};

pub const SendEventData = union(enum) {
    identify: send_events.Identify,
    @"resume": send_events.Resume,
    heartbeat: send_events.Heartbeat,
    request_guild_members: send_events.RequestGuildMembers,
    request_soundboard_sounds: send_events.RequestSoundboardSounds,
    update_voice_state: send_events.UpdateVoiceState,
    update_presence: send_events.UpdatePresence,
};

pub const Opcode = enum(u64) {
    dispatch = 0,
    heartbeat = 1,
    identify = 2,
    presence_update = 3,
    voice_state_update = 4,
    @"resume" = 6,
    reconnect = 7,
    request_guild_members = 8,
    invalid_session = 9,
    hello = 10,
    heartbeat_ack = 11,
    _,

    pub const jsonStringify = jconfig.stringifyEnumAsInt;
};
