const std = @import("std");

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const allocator = init.arena.allocator();
    const args = try init.minimal.args.toSlice(allocator);
    if (args.len != 2) {
        std.debug.panic("wrong number of arguments", .{});
    }

    const output_file_path = args[1];

    var output_file = try std.Io.Dir.cwd().createFile(io, output_file_path, .{});
    defer output_file.close(io);

    try output_file.writePositionalAll(io, try generateEndpointClient(io, allocator), 0);
}

fn generateEndpointClient(io: std.Io, arena: std.mem.Allocator) ![]u8 {
    const template_path = "./src/rest/EndpointClient.zig.template";

    const endpoints = try getEndpointFileNames(io, arena);
    const decls = try endpointDecls(io, arena, endpoints);
    var aw = std.Io.Writer.Allocating.init(arena);
    defer aw.deinit();
    try aw.writer.writeAll(try std.Io.Dir.cwd().readFileAlloc(io, template_path, arena, .limited(100_000)));
    try aw.writer.writeAll(decls);
    try aw.writer.flush();

    return aw.toOwnedSlice();
}

fn getEndpointFileNames(io: std.Io, arena: std.mem.Allocator) ![][]u8 {
    var file_names: std.ArrayList([]u8) = try .initCapacity(arena, 100);

    const dir = try std.Io.Dir.cwd().openDir(io, "./src/rest/endpoints", .{ .iterate = true });
    var iter = dir.iterateAssumeFirstIteration();
    while (try iter.next(io)) |file| {
        try file_names.append(arena, try arena.dupe(u8, file.name));
    }

    std.sort.insertion([]u8, file_names.items, .{}, asciiLessThanWithCtx);

    return file_names.toOwnedSlice(arena);
}

fn endpointDecls(io: std.Io, arena: std.mem.Allocator, endpoint_files: []const []const u8) ![]u8 {
    var new_contents_aw = try std.Io.Writer.Allocating.initCapacity(arena, 100_000);
    var new_contents = &new_contents_aw.writer;

    try new_contents.writeByte('\n');
    try new_contents.writeAll("// === generated by generate_endpoint_client.zig ===\n");
    for (endpoint_files) |endpoint_file| {
        const endpoint_from_cwd = try std.fmt.allocPrint(arena, "./src/rest/endpoints/{s}", .{endpoint_file});
        const endpoint = endpoint_file[0 .. endpoint_file.len - ".zig".len];
        try new_contents.print("pub const {s} = @import(\"./endpoints/{s}\");\n", .{ endpoint, endpoint_file });
        for (try publicTopLevelDecls(io, arena, endpoint_from_cwd)) |func_name| {
            try new_contents.print("pub const {s} = {s}.{0s};\n", .{ func_name, endpoint });
        }
    }
    return try new_contents_aw.toOwnedSlice();
}

fn publicTopLevelDecls(io: std.Io, arena: std.mem.Allocator, file_path: []const u8) ![][]u8 {
    var decls: std.ArrayList([]u8) = try .initCapacity(arena, 100);

    var buf: [10_000]u8 = undefined;
    var file = try std.Io.Dir.cwd().openFile(io, file_path, .{});
    var file_reader = file.reader(io, &buf);
    while (try file_reader.interface.takeDelimiter('\n')) |line| {
        if (std.mem.startsWith(u8, line, "pub fn")) {
            const start = "pub fn ".len;
            const end = std.mem.indexOfScalar(u8, line, '(') orelse return error.NoParenthesis;
            const func_name = try arena.dupe(u8, line[start..end]);
            try decls.append(arena, func_name);
        }
        if (std.mem.startsWith(u8, line, "pub const")) {
            const start = "pub const ".len;
            const end = std.mem.indexOfScalarPos(u8, line, start, ' ') orelse return error.NoIdentifierEnd;
            const const_name = try arena.dupe(u8, line[start..end]);
            try decls.append(arena, const_name);
        }
    }

    std.sort.insertion([]u8, decls.items, .{}, asciiLessThanWithCtx);

    return decls.toOwnedSlice(arena);
}

fn asciiLessThanWithCtx(_: @TypeOf(.{}), lhs: []u8, rhs: []u8) bool {
    return std.ascii.lessThanIgnoreCase(lhs, rhs);
}
